image: docker.corefacility.ca:5000/import-tool-for-galaxy_build:latest

variables:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_DATABASE: "external_galaxy_test"
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"
  #MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - .m2
  #  - ./tests/integration/repos
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

services:
  - mysql:5.6

before_script:
  - source .ci/install_deps.sh

test:
  script:
    - cd irida_import
    - xvfb-run py.test -s
